### ISSUE TITLE
¿ Cómo obtener los votos en blancos y nulos ?

### ISSUE THREAD

**Issue by Ren14** [pmoracho/paso2019#1]
Hola !

En base a tus tablas, como podría obtener el la cantidad de votos blancos y nulos por mesas ?

Gracias.

**Comment by pmoracho** [comment]
Respondo de todas formas

### Los votos en blanco, desde el modelo nuevo:

Los votos en blanco, en el modelo original, no tienen una entidad como si lo tienen las agrupaciones, por esto, en el nuevo modelo, los incorporé como si fueran un lista o partido "VOTOS en BLANCO". 

```
library(paso2019)
library(tidyverse)

votos %>% 
  filter(id_lista == 1443, # Lista ficticia para los votos en blanco
         votos > 0) %>% 
  left_join(categorias, by="id_categoria") %>% 
  left_join(mesas, by="id_mesa") %>% 
  group_by(nombre_categoria, codigo_mesa) %>% 
  summarize(votos_en_blanco=sum(votos))
```

### Los votos nulos

En el modelo nuevo, no trasladé más que los votos en blanco, imagino que cuando hablas de nulos son el resto de los votos que no son válidos y en blanco. Hay varias categorías, que se pueden consultar desde la tabla `mesas_totales`, por ejemplo en la categoría "Presidente y vice":

```
mesas_totales %>% 
  filter(CODIGO_CATEGORIA == "000100000000000") %>% 
  group_by(CODIGO_CATEGORIA,CONTADOR) %>% 
  summarise(votos = sum(VALOR))

# A tibble: 6 x 3
# Groups:   CODIGO_CATEGORIA [1]
  CODIGO_CATEGORIA CONTADOR  votos
  <chr>            <chr>     <dbl>
1 000100000000000  CSCCC     16382
2 000100000000000  CSDU         45
3 000100000000000  VB       758988
4 000100000000000  VII        6155
5 000100000000000  VN       300019
6 000100000000000  VR        13170
```
En la pagina  se mencionan 758.955 en blanco (VB), 300.019 nulos (VN) y Recurridos,Impugnados y Comando: (el resto de los códigos) 35.707. Los números son muy cercanos pero no exactos, hay evidentemente una diferencia entre los datos que se descargan de la página y los que efectivamente se terminan mostrando.
