### ISSUE TITLE
Obtener nombre de escuelas y sus mesas correspondientes

### ISSUE THREAD

**Issue by Ren14** [pmoracho/paso2019#2]
Buenos días

¿ Cómo puedo obtener los nombres de las escuelas y la relación con sus mesas ?

Gracias.

**Comment by pmoracho** [comment]
Lamentablemente, en los archivos originales , no existe está información. Estoy investigando si de alguna otra fuente se puede encontrar algo. Dejo abierto este "issue" por ahora.

**Comment by Ren14** [comment]
Lo pude hacer, pero de forma semi-automática. Te comento como lo hice.
En el sitio web donde publicaron los resultados https://www.resultados2019.gob.ar/, si "escuchas" con la consola en la pestaña de network, prestá atención al onchange de los circuitos electorales, vas a ver que en la primer petición, realiza una llamada a un JSON. Ahí obtiene las escuelas. Luego dentro de cada elemento del Json de escuelas, está otro JSON que contiene las mesas asociadas a la escuela. 

Ojo tenes que acceder al método por CURL, no por AJAX.

Abrazo.-

**Comment by pmoracho** [comment]
Gracias, por el dato. Voy a investigarlo, tal vez se pueda armar algún proceso de scrapping para obtener los datos completos

**Comment by pmoracho** [comment]
Renzo, efectivamente pude recabar el 99.99% de los establecimientos y las mesas de esta forma, hubo unos poco casos que tuve que cargarlos manualmente. Hay dos tablas nuevas `scrap_establecimientos_mesas` que es la versión cruda del proceso de todos los json y `establecimientos` que tiene los datos más adecuados al modelo nuevo, también a `mesas` le agregué el `establecimiento_id`. Cualquier cosa decime. Saludos.
